# Generated by Django 5.1.15 on 2026-03-05 12:06

from django.db import migrations

def seed_drivers(apps, schema_editor):
    Driver = apps.get_model("industrial_config_manager", "Driver")

    drivers = [
        ("opcua", "OPC UA", "OPC-UA"),
        ("snap7", "Siemens S7", "Snap7"),
        ("modbus", "Modbus TCP", "Modbus"),
    ]

    for code, name, protocol in drivers:
        Driver.objects.get_or_create(
            code=code,
            defaults={
                "name": name,
                "protocol": protocol,
                "description": f"{name} industrial driver"
            }
        )

class Migration(migrations.Migration):

    dependencies = [
        ("industrial_config_manager", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_drivers),
    ]