# Generated by Django 5.1.15 on 2026-03-20 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industrial_config_manager', '0002_seed_drivers'),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_id', models.CharField(max_length=100)),
                ('property', models.CharField(max_length=50)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='industrial_config_manager.tag')),
            ],
            options={
                'ordering': ['widget_id'],
                'unique_together': {('widget_id', 'property')},
            },
        ),
    ]
