# Generated by Django 5.1.15 on 2026-03-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industrial_config_manager', '0003_widgetbinding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='fc',
            field=models.IntegerField(blank=True, choices=[(1, 'FC1 - Read Coils'), (2, 'FC2 - Read Discrete Inputs'), (3, 'FC3 - Read Holding Registers'), (4, 'FC4 - Read Input Registers')], null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Short standardized name', max_length=100),
        ),
    ]
