########################################
# CUSTOMER A
########################################

# Gateway customerA (solo publica)
user customerA
topic write customerA/#

# Ingestor / Telegraf customerA (solo lee ingest)
user ingest_customerA
topic read customerA/#

# (Opcional) SCADA customerA
user scada_customerA
topic read ingest/customerA/#
topic write cmd/customerA/#

########################################
# CUSTOMER B
########################################

# Gateway customerA (solo publica)
user customerB
topic write customerB/#

# Ingestor / Telegraf customerA (solo lee ingest)
user ingest_customerB
topic read customerB/#

########################################
# Admin opcional
########################################

user admin
topic readwrite #
