########################################
# CUSTOMER A
########################################

# --- Gateway customerA ---
user customerA
topic write customerA/#
topic read  customerA/#
topic read  $SYS/#

# --- Ingest customerA ---
user ingest_customerA
topic read customerA/#

########################################
# CUSTOMER B
########################################

user gw_customer_B
topic write customer_B/#
topic read  $SYS/#

user ingest_customer_B
topic read customer_B/#

########################################
# Admin opcional
########################################

user admin
topic readwrite #
