# ===============================
# Broker MQTT - Mosquitto Config
# ===============================

# Permitir conexión por TCP desde clientes internos (p.ej. gateway, telegraf)
listener 1883 0.0.0.0
protocol mqtt

# (opcional) listener por WebSocket
listener 9001 0.0.0.0
protocol websockets

# Archivos de autenticación (comentado si no usas usuarios)
# password_file /mosquitto/config/passwords.txt
# allow_anonymous false

# ¡OJO!Permitir conexiones anónimas en entorno de desarrollo
allow_anonymous false
password_file /mosquitto/config/passwords
acl_file /mosquitto/config/acls.conf
max_connections -1  


# Archivos de persistencia (retained messages)
persistence true
persistence_location /mosquitto/data/

# Donde guardar logs
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information

# Verbosidad de logs
connection_messages true
log_timestamp true


# Plugins, TLS, y otras opciones avanzadas están desactivadas aquí
# (puedes extender más adelante si necesitas autenticación con certificados)