# ===============================
# Broker MQTT - Mosquitto Config
# ===============================

# Puerto estándar MQTT
listener 1883 0.0.0.0
protocol mqtt

# Puerto WebSockets para React
listener 9001 0.0.0.0
protocol websockets

# --- EL CAMBIO ESTÁ AQUÍ ---
# Permitir conexiones mientras estamos en desarrollo
allow_anonymous true

# Comentamos esto temporalmente para que no bloquee si los archivos están vacíos
# password_file /mosquitto/config/passwords
# acl_file /mosquitto/config/acls.conf
# ---------------------------

max_connections -1  

# Persistencia
persistence true
persistence_location /mosquitto/data/

# Logs
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
connection_messages true
log_timestamp true