# ================================
#  TELEGRAF PRODUCCIÓN
#  Input:  mqtt_prod
#  Output: bucket "scada"
# ================================

[agent]
  interval = "10s"
  flush_interval = "10s"
  debug = false
  quiet = false

# -------------------------------
# INPUT MQTT PRODUCCIÓN
# -------------------------------
[[inputs.mqtt_consumer]]
  # name_override = "mqtt_prod"
  servers = ["tcp://mosquitto:1883"]
  topics = ["plant/+/area/+/line/+/cell/+/equip/+/tag/#"]
  client_id = "telegraf_scada_client"
  qos = 0
  persistent_session = false
  connection_timeout = "30s"
  data_format = "json_v2"
  tagexclude = ["topic"]

  [[inputs.mqtt_consumer.json_v2]]
    measurement_name = "plc_tags"
    # El timestamp del dato es el que viene dentro del mensaje
    timestamp_path = "timestamp"
    timestamp_format = "2006-01-02T15:04:05.999999999Z07:00"

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "value_bool"
      optional = true

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "value_int"
      optional = true

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "value_float"
      optional = true

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "value_str"
      optional = true

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "value_time"
      optional = true

    [[inputs.mqtt_consumer.json_v2.tag]]
      path = "equipment_id"

    [[inputs.mqtt_consumer.json_v2.tag]]
      path = "variable"

    [[inputs.mqtt_consumer.json_v2.tag]]
      path = "unit"

    [[inputs.mqtt_consumer.json_v2.tag]]
      path = "datatype"

# -------------------------------
# OUTPUTS
# -------------------------------

# Debug opcional:
[[outputs.file]]
  files = ["stdout"]
  data_format = "json"

# Producción:
[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "d55k6GoWTb2VFHPInrF72xcx5R20THh-CJn2KRIZai3m-P_58FQDreODcpGq6DlVGSSDmDIZjIRZnG5qFAOacw=="
  organization = "acme"
  bucket = "scada"
