services:
  postgres:
    image: postgres:16
    container_name: wire-deploy-postgres
    restart: always
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django1234
      POSTGRES_DB: industry4_v2
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_v2:/var/lib/postgresql/data
    networks:
      - suite-central-net


  # ---------- BACKEND CORE ----------
  django-api:
      build:
        context: ./django-api
      container_name: django-api
      volumes:
        - ./django-api:/app
        - ./opt/suite/config:/opt/suite/config
        - /var/run/docker.sock:/var/run/docker.sock
      env_file:
        - .env
      environment:
        - DJANGO_SETTINGS_MODULE=core.settings
        - PYTHONUNBUFFERED=1
        - TZ=Europe/Madrid

        # Postgres
        - POSTGRES_HOST=postgres
        - POSTGRES_DB=industry4_v2
        - POSTGRES_USER=django
        - POSTGRES_PASSWORD=django1234

        # Docker
        - DOCKER_HOST=unix:///var/run/docker.sock

      ports:
        - "8000:8000"
      depends_on:
        - postgres
      command: python manage.py runserver 0.0.0.0:8000
      networks:
        - suite-central-net

  django-ws:
    build:
      context: ./django-api
    container_name: django-ws
    command: daphne -b 0.0.0.0 -p 8002 core.asgi:application
    ports:
      - "8002:8002"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Madrid
    depends_on:
      - postgres
    networks:
      - suite-central-net


  # ---------- FRONTEND ----------
  frontend:
    build: ./frontend
    container_name: wire-deploy-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      VITE_API_URL: http://django-api:8000
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "5173:5173"
    depends_on:
      - django-api
    networks:
      - suite-central-net

  redis-to-ws:
    build:
      context: ./django-api
    container_name: redis-to-ws
    command: python manage.py redis_to_websocket --tenants=customerA
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6379
      - TENANTS=customerA
    networks:
      - suite-central-net
    extra_hosts:
      - "host.docker.internal:host-gateway"
      
# ---------- VOLUMES ----------
volumes:
  postgres_data_v2:

# ---------- NETWORKS ----------
networks:
  suite-central-net:
    driver: bridge
    name: suite-central-net