# ===== OPC UA Gateway Mapping =====
driver: "opcua"

connection:
  # endpoint:  "opc.tcp://127.0.0.1:4840/freeopcua/server/"
  endpoint: opc.tcp://host.docker.internal:4840/freeopcua/server/
  namespace_uri: "http://ebw-itp.local"
  # seguridad opcional
  security_mode: "SignAndEncrypt"
  security_policy: "Basic256Sha256"
  certificate: "client_cert.der"
  private_key: "client_key.pem"
  cert_uri: "urn:gateway:uri" 
  timeouts_ms:
    connect: 5000
    session: 10000
  reconnect:
    enable: true
    min_delay_ms: 1000
    max_delay_ms: 10000

# Identidad lógica CDC del equipo
equipment_id: "DemoIPT/vivex/VIVEX_SIM"

# Suscripción (modo data change)
subscription:
  publishing_interval_ms: 500
  sampling_interval_ms: 200
  queue_size: 10
  discard_oldest: true

# Política común
defaults:
  quality_on_bad: "drop"
  deadband:
    type: "none"
    value: 0
  on_change_only: false

# ===== Señales a leer =====
items:
  # --- Variable Float Vivex1 ---
  - name: "VIVEX_1"
    addressing:
      node_id: "ns=2;s=IBH_VIVEX.IBH_VIVEX.PLC_EW172"      
    datatype: "Float"
    cdc:
      tag: "process/test_vivex1"
      unit: "-"
      description: "Variable de estado vivex2"
    overrides:
      sampling_interval_ms: 200

  # --- Variable Float Vivex2 ---
  - name: "VIVEX_2"
    addressing:
      node_id: "ns=2;s=IBH_VIVEX.IBH_VIVEX.PLC_EW174"
    datatype: "Float"
    cdc:
      tag: "process/test_vivex1"
      unit: "-"
      description: "Variable de estado vivex2"

# Emisión (modo consola para pruebas)
publish:
  mode: "pretty"                     # imprime los CDC tags en consola
