# ===============================================================
# GATEWAY ROOT CONFIGURATION
# Este archivo orquesta todos los PLCs/Drivers del sistema SCADA.
# ===============================================================

gateway:
  name: "scada-gw-01"         # ← Identificador lógico del gateway (usado en logs, métricas, etc.)
  log_level: "INFO"           # ← Nivel de logging global: DEBUG, INFO, WARNING, ERROR

  publisher:                  # ← Define cómo se emiten los datos CDC que vienen de los drivers
    # mode: "pretty"            # ← pretty | stdout | mqtt | http | function
    mode: "mqtt"              
    url: "tcp://mosquitto:1883" 
    topic_prefix: "plant"     # Modulable en _topic_for_tag
    # mqtt:                   # (solo si eliges modo "mqtt")
    #   broker_url: "mqtt://192.168.0.100:1883"
    #   topic_template: "plant/{equipment_id}/{tag}"
    # mode: "function"
    # target: "gateway.publisher.cdc_publisher"  # ruta del callable Python
    # mosquitto_sub -h 127.0.0.1 -p 1883 -t "plant/#" -v ***SUSCRIPTOR DE CONSOLA***


    # mosquitto con docker
    # mode: mqtt
    # url: tcp://mosquitto:1883
    # topic_prefix: plant

    
    


# ---------------------------------------------------------------
# Defaults globales: aplican a todos los PLCs salvo override.
# Cada equipo puede sobreescribir estas políticas localmente.
# ---------------------------------------------------------------
defaults:
  # -- Para drivers OPC UA (lectura por suscripción) --
  subscription:
    publishing_interval_ms: 500    # Cada cuánto el server agrupa notificaciones
    sampling_interval_ms: 200      # Cada cuánto muestrea internamente las variables
    queue_size: 10
    discard_oldest: true

  # -- Para drivers S7 (lectura por polling) --
  polling:
    interval_ms: 5000               # Periodo de lectura cíclica de Snap7

  # -- Política común de datos --
  on_change_only: false             # Solo emitir si el valor cambia
  quality_on_bad: "drop"           # drop | last | null → qué hacer si la lectura tiene mala calidad
  deadband:                        # Filtrado de ruido (opcional)
    type: "none"                   # none | absolute | percent
    value: 0





# ---------------------------------------------------------------
# Lista de equipos gestionados por este gateway
# Cada uno apunta a su propio archivo YAML modular (por PLC)
# ---------------------------------------------------------------
equipments:
  # - items_file: "configs/opcua_demoserver.yaml"   # ← PLC OPC UA (servidor demo)
  # - items_file: "configs/opcua_test1.yaml"     # ← PLC OPC UA (ejemplo PLC Alberto)
  # - items_file: "configs/s7_test1.yaml"     # ← PLC Snap7 (ejemplo PLC Alberto)
  # - items_file: "configs/s7_test2.yaml"     # PLC real Unai
  # - items_file: "configs/config_itp.yaml"   # ← PLC OPC UA (servidor itp)
  - items_file: "configs/termo_config.yaml"   # ← PLC OPC UA (servidor demo temperatura)
  - items_file: "configs/valve_config.yaml"   # ← PLC OPC UA (servidor demo válvula)
  # - items_file: "configs/modbus_model.yaml"
  - items_file: "configs/modbus2.yaml"
