equipment_id: planta2/area2/linea2/cell2/equipo02
driver: modbus

connection:
  host: "192.168.0.13"
  port: 502
  unit_id: 1
  poll_rate_ms: 1000

modbus_format:
  byte_order: "big"      # Siemens usa Big Endian
  word_order: "big"

items:
  # Ejemplo de configuración típica PAC3220:
  # (Actualiza con las direcciones reales de tu scanner)

  - variable: "tension_linea_1"
    address: 1
    datatype: "Float"
    unit: "V"
    fc: 4

  # - variable: "current_l1"
  #   address: 10
  #   datatype: "Float"
  #   unit: "A"
  #   fc: 4

  # - variable: "active_power_total"
  #   address: 49
  #   datatype: "Float"
  #   unit: "W"
  #   fc: 4

  # - variable: "frequency"
  #   address: 55
  #   datatype: "Float"
  #   unit: "Hz"
  #   fc: 4