equipment_id: planta1/area1/linea1/cell1/equipo01
driver: modbus

connection:
  host: "192.168.100.94"
  port: 502
  poll_rate_ms: 500

modbus_format:
  byte_order: "big"      # "big" o "little"
  word_order: "little"



items:
  # Datos confirmados (válidos, valores consistentes)
  - variable: total_current
    address: 1012
    datatype: Float
    fc: 4
    unit: "VA"
    # format: OVERRIDE JUST IN CASE
        #   byte_order: "little"
        #   word_order: "big"

  - variable: c_aprt_power
    address: 1016
    datatype: Float
    fc: 4
    unit: "A"
    modbus_format:
      byte_order: "big"      # "big" o "little"
      word_order: "big"


  - variable: a_current
    address: 1042
    datatype: Float
    fc: 4
    unit: "A"

  - variable: "current_phase_c_alt1"
    address: 1022
    datatype: "Float"
    unit: "A"
    fc: 4
    format:
      byte_order: "little"
      word_order: "little"

  - variable: c_voltage
    address: 1060
    datatype: Float
    fc: 4
    unit: "W"
    # modbus_format:
    #   byte_order: "big"      # "big" o "little"
    #   word_order: "little"

  # # Opcionales — contienen valores pero pueden no tener sentido físico
  # - variable: raw_value_0
  #   address: 0
  #   datatype: Float
  #   fc: 4
  #   unit: ""

  # - variable: raw_value_6
  #   address: 6
  #   datatype: Float
  #   fc: 4
  #   unit: ""

  # - variable: raw_value_8
  #   address: 8
  #   datatype: Float
  #   fc: 4
  #   unit: ""

  # - variable: raw_value_12
  #   address: 12
  #   datatype: Float
  #   fc: 4
  #   unit: ""
  # - variable: csp1
  #   address: 899
  #   datatype: Float
  #   fc: 3
  #   unit: "°F"

  # - variable: outdoor_temp
  #   address: 3
  #   datatype: Float
  #   fc: 4
  #   unit: "°C"

  # - variable: alarm_freeze
  #   address: 0
  #   datatype: Bool
  #   fc: 1

  # - variable: csp2
  #   address: 901
  #   datatype: Float
  #   unit: "°F"

  # - variable: ice_sp
  #   address: 903
  #   datatype: Float
  #   unit: "°F"

  # - variable: ice_config
  #   address: 4099
  #   datatype: Float
  #   unit: "°F"

  # - variable: pow_max
  #   address: 4117
  #   datatype: Float

  # - variable: pow_sel
  #   address: 4119
  #   datatype: Float
