# Conexión S7 le decimos qué leer y cómo leer
driver: "snap7"
ip: "10.100.100.15"     # ← pon la IP real del PLC
rack: 0                # S7-300/400: normalmente 0; S7-1200/1500: suele ser 0
slot: 1                # S7-300: CPU a menudo en slot 2; S7-1200/1500: normalmente 1
timeout_ms: 2000       # opcional
pdu_size: 960          # opcional, si lo necesitas

# Identidad lógica (CDC)
equipment_id: "Line1/SiteUnai/PLC_S7"

# Política de lectura
mode: "polling"
# poll_ms: 500           # lee cíclicamente cada 500 ms (para el probe continuo)
# batch_by_db: true      # agrupa lecturas por DB para eficiencia

# Items: DB absolutos (no optimizados)
items:
  # # DB<numero>.DB<tipo><offset>
  - address: "DB1.DBW0"
    variable: "status_code"
    datatype: "Int16"
    unit: "-"
