# Generated by Django 5.1.15 on 2026-02-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerbi_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mypowerbi',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='mypowerbi',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
