driver: opcua
equipment_id: customerA/Planta1/Horno1/Temperatura
connection:
  endpoint: opc.tcp://host.docker.internal:4840/freeopcua/server/
  namespace_uri: http://customerA-simulator.local
  security_mode: None
  security_policy: None
  timeouts_ms:
    connect: 5000
    session: 10000
  reconnect:
    enable: true
    min_delay_ms: 1000
    max_delay_ms: 10000

isa95:
  site: customerA
  area: Planta1
  work_center: Horno1
  work_unit: SensorTemperatura

items:
  - name: temperatura_horno
    datatype: Float
    cdc:
      tag: process/temperatura_horno
      unit: ºC
    addressing:
      node_id: ns=2;s=Process.Temperature
