# ================================
#  TELEGRAF PRODUCCIÓN
#  Input:  mqtt_prod
#  Output: bucket "scada"
# ================================

[agent]
  interval = "10s"
  flush_interval = "10s"
  debug = true
  quiet = false

# -------------------------------
# INPUT MQTT PRODUCCIÓN
# -------------------------------
[[inputs.mqtt_consumer]]
  servers  = ["${MQTT_SERVER}"]
  username = "${MQTT_USER}"
  password = "${MQTT_PASS}"

  topics = ["customerA/#"]

  client_id = "telegraf_customerA"
  qos = 1
  persistent_session = true

  connection_timeout = "30s"
  data_format = "json_v2"
  tagexclude = ["topic"]

  [[inputs.mqtt_consumer.json_v2]]
    measurement_name = "plc_tags"
    # El timestamp del dato es el que viene dentro del mensaje
    timestamp_path = "timestamp"
    # timestamp_format = "2006-01-02T15:04:05.999999999Z07:00"
    timestamp_format = "unix_ms"

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "value_bool"
      optional = true

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "value_int"
      optional = true

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "value_float"
      optional = true

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "value_str"
      optional = true

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "value_time"
      optional = true

    [[inputs.mqtt_consumer.json_v2.tag]]
      path = "equipment_id"

    [[inputs.mqtt_consumer.json_v2.tag]]
      path = "variable"

    [[inputs.mqtt_consumer.json_v2.tag]]
      path = "unit"

    [[inputs.mqtt_consumer.json_v2.tag]]
      path = "datatype"

    [[inputs.mqtt_consumer.json_v2.tag]]
      path = "quality"

# -------------------------------
# OUTPUTS
# -------------------------------

# Debug opcional:
# [[outputs.file]]
#   files = ["stdout"]
#   data_format = "json"

# Producción:
[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "${INFLUX_TOKEN_DEPLOYMENT}"
  organization = "${INFLUX_ORG}"
  bucket = "${INFLUX_BUCKET}"
