gateway:
  name: gateway-customerA
  tenant: customerA
  log_level: INFO
  publisher:
    mode: mqtt
    url: tcp://mosquitto:1883
    topic_prefix: customerA

defaults:
  subscription:
    publishing_interval_ms: 500
    sampling_interval_ms: 200
    queue_size: 10
    discard_oldest: true

equipments:
  - items_file: /opt/suite/config/plc/customerA_temp.yaml
  - items_file: /opt/suite/config/plc/customerA_flow.yaml
