# Generated by Django 5.1.15 on 2026-02-05 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_manager', '0003_alter_role_scopes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='map_manager.factory')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('gps_x', models.FloatField(blank=True, null=True)),
                ('gps_y', models.FloatField(blank=True, null=True)),
                ('direction', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=20)),
                ('llevar_a_url', models.CharField(blank=True, help_text="URL a la que llevar al hacer clic en 'Ir al sitio'", max_length=200, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='auth_manager.client')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='map_manager.country')),
            ],
        ),
        migrations.AddField(
            model_name='factory',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='map_manager.location'),
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='map_manager.country')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=50)),
                ('operating_mode', models.CharField(choices=[('Automatic', 'Automatic'), ('Semi-automatic', 'Semi-automatic'), ('Manual', 'Manual')], max_length=20)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='map_manager.area')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='map_manager.manufacturer')),
            ],
        ),
    ]
