# Generated by Django 5.1.15 on 2026-01-26 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scada_manager.factory')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('gps_x', models.FloatField(blank=True, null=True)),
                ('gps_y', models.FloatField(blank=True, null=True)),
                ('direction', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=20)),
                ('llevar_a_url', models.CharField(blank=True, help_text="URL a la que llevar al hacer clic en 'Ir al sitio'", max_length=200, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scada_manager.country')),
            ],
        ),
        migrations.AddField(
            model_name='factory',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scada_manager.location'),
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scada_manager.country')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=50)),
                ('operating_mode', models.CharField(choices=[('Automatic', 'Automatic'), ('Semi-automatic', 'Semi-automatic'), ('Manual', 'Manual')], max_length=20)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='scada_manager.area')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scada_manager.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='MyLayOutsTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_name', models.CharField(max_length=200)),
                ('views_data', models.JSONField(blank=True, help_text='JSON containing multiple views for multi-window applications', null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyLayOut',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('data', models.JSONField()),
                ('button_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scada_manager.mylayoutstitle')),
            ],
        ),
    ]
