# Generated by Django 5.1.15 on 2026-03-05 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_manager', '0003_alter_role_scopes'),
        ('scada_manager', '0004_alter_mylayoutstitle_options_mylayoutstitle_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTagGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_groups', to='auth_manager.client')),
            ],
            options={
                'db_table': 'scada_custom_tag_group',
                'unique_together': {('name', 'client')},
            },
        ),
        migrations.CreateModel(
            name='CustomTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100)),
                ('equipment_id', models.CharField(max_length=255)),
                ('cdc_tag', models.CharField(max_length=255)),
                ('datatype', models.CharField(default='Float', max_length=50)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('node_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='scada_manager.customtaggroup')),
            ],
            options={
                'db_table': 'scada_custom_tag',
                'unique_together': {('group', 'tag_name')},
            },
        ),
    ]
