# Generated by Django 5.1.15 on 2026-03-16 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada_manager', '0005_projectvariable'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_tables', to='scada_manager.mylayoutstitle')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('layout', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='projectvariable',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='projectvariable',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='scada_manager.variabletable'),
        ),
        migrations.AlterUniqueTogether(
            name='projectvariable',
            unique_together={('table', 'name')},
        ),
        migrations.RemoveField(
            model_name='projectvariable',
            name='layout',
        ),
    ]
