# Generated by Django 5.1.15 on 2026-03-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada_manager', '0006_variabletable_alter_projectvariable_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectvariable',
            name='equipment_id',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
