import gaugeDefaultIcon from "@/assets/icons/gaugeDefault.svg";

export const elementos_scada = {
  gauges: [
    {
      id: "tpl-temp-gauge",
      title: "Temp Gauge",
      thumbnailUrl: gaugeDefaultIcon, // Reusamos icono por ahora
      data: {
        type: "temp-gauge",
        width: "auto",
        height: 220,
        label: "Temperatura",
        settings: { min: 0, max: 120, unit: "°C" },
      },
    },
    {
      id: "tpl-hmi-scada-gauge-thermal",
      title: "SCADA Gauge Thermal",
      thumbnailUrl: gaugeDefaultIcon,
      data: {
        type: "hmi-scada-gauge",
        width: 220,
        height: 220,
        label: "Reactor_Temp_01",
        settings: {
          unit: "CELSIUS",
          min: 0,
          max: 200,
          themeColor: "#f43f5e",
          initialValue: 140,
          zones: [
            { start: 160, end: 200, color: "#f43f5e" },
            { start: 130, end: 160, color: "#f59e0b" },
          ],
        },
      },
    },
    {
      id: "tpl-hmi-scada-gauge-pressure",
      title: "SCADA Gauge Pressure",
      thumbnailUrl: gaugeDefaultIcon,
      data: {
        type: "hmi-scada-gauge",
        width: 220,
        height: 220,
        label: "Hydraulic_Press_04",
        settings: {
          unit: "BAR / PSI",
          min: 0,
          max: 10,
          themeColor: "#06b6d4",
          initialValue: 4.5,
          zones: [{ start: 4, end: 7, color: "#10b981" }],
        },
      },
    },
    {
      id: "tpl-hmi-scada-gauge-flow",
      title: "SCADA Gauge Flow",
      thumbnailUrl: gaugeDefaultIcon,
      data: {
        type: "hmi-scada-gauge",
        width: 220,
        height: 220,
        label: "Load_Flow_Main",
        settings: {
          unit: "M3/HR",
          min: 0,
          max: 1000,
          themeColor: "#f59e0b",
          initialValue: 700,
          zones: [{ start: 850, end: 1000, color: "#f43f5e" }],
        },
      },
    },
    {
      id: "tpl-hmi-horizontal-gauge-precision",
      title: "Horizontal Gauge Precision",
      thumbnailUrl: gaugeDefaultIcon,
      data: {
        type: "hmi-horizontal-gauge",
        width: 240,
        height: 140,
        label: "PT-102",
        settings: {
          min: 0,
          max: 10,
          initialValue: 4.2,
          unit: "BAR",
          variant: "precision",
          accentColor: "#1e293b",
        },
      },
    },
    {
      id: "tpl-hmi-horizontal-gauge-heavy",
      title: "Horizontal Gauge Heavy",
      thumbnailUrl: gaugeDefaultIcon,
      data: {
        type: "hmi-horizontal-gauge",
        width: 240,
        height: 140,
        label: "ST-405",
        settings: {
          min: 0,
          max: 60,
          initialValue: 32,
          unit: "RPM x100",
          variant: "heavy",
          accentColor: "#1e40af",
        },
      },
    },
    {
      id: "tpl-hmi-horizontal-gauge-arc",
      title: "Horizontal Gauge Arc",
      thumbnailUrl: gaugeDefaultIcon,
      data: {
        type: "hmi-horizontal-gauge",
        width: 240,
        height: 140,
        label: "TT-099",
        settings: {
          min: 0,
          max: 100,
          initialValue: 55,
          unit: "°C",
          variant: "arc",
          accentColor: "#be123c",
        },
      },
    },
  ],
  barras: [
    {
      id: "tpl-hmi-progress-bar",
      title: "Barra HMI",
      thumbnailUrl: gaugeDefaultIcon,
      data: {
        type: "hmi-progress-bar",
        width: 450,
        height: 90,
        label: "LOREM IPSUM",
        settings: {
          minValue: 0,
          maxValue: 100,
          initialValue: 66,
          caption: "LOREM IPSUM",
        },
      },
    },
    {
      id: "tpl-hmi-tank-level",
      title: "Tanque Cilíndrico",
      thumbnailUrl: gaugeDefaultIcon,
      data: {
        type: "hmi-tank-level",
        width: 150,
        height: 200,
        label: "Nivel",
        settings: {
          minValue: 0,
          maxValue: 100,
          initialValue: 50,
        },
      },
    },
  ],
  tarjetas: [
    {
      id: "tpl-hmi-status-ok",
      title: "Status OK",
      thumbnailUrl: gaugeDefaultIcon,
      data: {
        type: "hmi-status-card",
        width: 280,
        height: 90,
        label: "SISTEMA OK",
        settings: {
          status: "ok",
          title: "SISTEMA OK",
          subtitle: "STATUS: READY",
        },
      },
    },
    {
      id: "tpl-hmi-status-warning",
      title: "Status Warning",
      thumbnailUrl: gaugeDefaultIcon,
      data: {
        type: "hmi-status-card",
        width: 280,
        height: 90,
        label: "AVISO / REVISIÓN",
        settings: {
          status: "warning",
          title: "AVISO / REVISIÓN",
          subtitle: "STATUS: WARNING",
        },
      },
    },
    {
      id: "tpl-hmi-status-emergency",
      title: "Status Emergency",
      thumbnailUrl: gaugeDefaultIcon,
      data: {
        type: "hmi-status-card",
        width: 280,
        height: 90,
        label: "EMERGENCY STOP",
        settings: {
          status: "emergency",
          title: "EMERGENCY STOP",
          subtitle: "STATUS: CRITICAL",
        },
      },
    },
    {
      id: "tpl-hmi-trend-card",
      title: "Tarjeta Dashboard",
      thumbnailUrl: gaugeDefaultIcon,
      data: {
        type: "hmi-trend-card",
        width: 400,
        height: 220,
        label: "Caudal de Proceso - Cuba 2",
        settings: {
          title: "Caudal de Proceso - Cuba 2",
          unitLabel: "LOREM IPSUM",
          minValue: 0,
          maxValue: 10000,
          initialValue: 5684,
          series: [110, 115, 108, 120, 130, 125, 140, 135, 150, 145],
        },
      },
    },
    {
      id: "tpl-hmi-energy-summary",
      title: "Tarjeta Energy Summary",
      thumbnailUrl: gaugeDefaultIcon,
      data: {
        type: "hmi-energy-summary",
        width: 380,
        height: 140,
        label: "Consumo Medido em Maio 2023",
        settings: {
          title: "Consumo Medido em Maio 2023",
          value: "1.627.009,26",
          unit: "kWh",
          subtitle: "Electric Energy",
          deltaText: "Higher than previous month",
          deltaValue: "2%",
          deltaDirection: "up",
        },
      },
    },
  ],
  graficas: [
    {
      id: "tpl-energy-bar-chart",
      title: "Energy Bar Chart",
      thumbnailUrl: gaugeDefaultIcon,
      data: {
        type: "energy-bar-chart",
        width: 400,
        height: 250,
        label: "CONSUMO ENERGÉTICO (kW)",
        settings: {
          title: "CONSUMO ENERGÉTICO (kW)",
          valueText: "420 kW",
        },
      },
    },
    {
      id: "tpl-temperature-line-chart",
      title: "Temperature Line Chart",
      thumbnailUrl: gaugeDefaultIcon,
      data: {
        type: "temperature-line-chart",
        width: 400,
        height: 250,
        label: "Temp °C",
        settings: {
          legendLabel: "Temp °C",
          pointLabel: "55ºC",
        },
      },
    },
  ],
};
