# Generated by Django 5.1.15 on 2026-02-27 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='city',
            new_name='name',
        ),
    ]
