# Generated by Django 5.1.15 on 2026-03-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='favorite',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
