services:
  gateway:
    build: ../../edge/gateway
    container_name: gateway_customerB
    env_file:
      - ./customerB.env
    environment:
      - TZ=Europe/Madrid
      - GATEWAY_CONFIG=/opt/suite/config/gateway.yaml
    volumes:
      - ./opt/suite/config:/opt/suite/config:ro
    restart: unless-stopped
    networks:
      - suite-central-net

  writer-mssql:
    build: ../../edge/writer_mssql
    container_name: writer_customerB
    env_file:
      - ./customerB.env
    depends_on:
      - mosquitto
      - sqlserver
    restart: unless-stopped
    networks:
      - suite-central-net

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_customerB
    env_file:
      - ./customerB.env
    ports:
      - "1434:1433"   # 🔥 puerto distinto
    volumes:
      - sqlserver_data_customerB:/var/opt/mssql
    networks:
      - suite-central-net

  # ---------- MOSQUITTO ----------
  mosquitto:
    image: eclipse-mosquitto:2.0.18
    container_name: mosquitto_customerB
    ports:
      - "127.0.0.1:1885:1883"
      - "127.0.0.1:9002:9001"
    volumes:
      - ./mosquitto:/mosquitto
      - mosquitto_data_customerB:/mosquitto/data
      - mosquitto_log_customerB:/mosquitto/log
    networks:
      - suite-central-net

  redis:
    image: redis:7
    container_name: redis_customerB
    restart: unless-stopped
 
    networks:
      - suite-central-net

  mqtt_bridge:
    build:
      context: ../../edge/core_backend
    container_name: mqtt_bridge_customerB
    command: python -m mqtt_bridge.run
    env_file:
      - ./customerB.env
    depends_on:
      - mosquitto
      - redis
    restart: unless-stopped
    networks:
      - suite-central-net

  redis-bridge:
    build:
      context: ../../edge/core_backend
    container_name: redis_bridge_customerB
    command: python -m realtime.redis_bridge
    env_file:
      - ./customerB.env
    environment:
      - LOCAL_REDIS_HOST=redis_customerB
      - LOCAL_REDIS_PORT=6379

      # 🔥 Redis CENTRAL (no local)
      - CENTRAL_REDIS_HOST=redis-central
      - CENTRAL_REDIS_PORT=6379

      # Identidad del cliente
      - TENANT_ID=customerB
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - suite-central-net

  core-backend:
    build:
      context: ../../edge/core_backend
    container_name: core-backendB
    volumes:
      - ../../edge/core_backend:/app
      - ../opt/suite/config:/opt/suite/config
    env_file:
      - ./customerB.env
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Madrid
    ports:
      - "8003:8000"   # 🔥 puerto distinto
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - suite-central-net

networks:
  suite-central-net:
    external: true
    name: suite-central-net


volumes:
  sqlserver_data_customerB:
  mosquitto_data_customerB:
  mosquitto_log_customerB:
