# Generated by Django 5.1.15 on 2026-01-26 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('protocol', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='industrial_config_manager.site')),
            ],
        ),
        migrations.CreateModel(
            name='WorkCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workcenters', to='industrial_config_manager.area')),
            ],
        ),
        migrations.CreateModel(
            name='WorkUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workunits', to='industrial_config_manager.workcenter')),
            ],
        ),
        migrations.CreateModel(
            name='PLC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('connection_string', models.CharField(max_length=255)),
                ('connection_data', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('config_path', models.CharField(blank=True, max_length=300)),
                ('equipment_id', models.CharField(editable=False, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='industrial_config_manager.driver')),
                ('work_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_modules', to='industrial_config_manager.workunit')),
            ],
            options={
                'ordering': ['work_unit', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short standardized name (e.g. pressure, cmd_start)', max_length=100)),
                ('datatype', models.CharField(choices=[('Boolean', 'Boolean'), ('Int16', 'Int16'), ('Int32', 'Int32'), ('UInt16', 'UInt16'), ('UInt32', 'UInt32'), ('Float', 'Float'), ('Double', 'Double'), ('String', 'String'), ('DateTime', 'DateTime'), ('Char', 'Char')], max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('fc', models.IntegerField(blank=True, choices=[(1, 'FC1 - Read Coils'), (2, 'FC2 - Read Discrete Inputs'), (3, 'FC3 - Read Holding Registers'), (4, 'FC4 - Read Input Registers')], help_text='Modbus Function Code (only for Modbus TCP driver)', null=True)),
                ('enabled', models.BooleanField(default=True, help_text='Whether this tag should be read from the PLC')),
                ('eng_min', models.FloatField(blank=True, null=True)),
                ('eng_max', models.FloatField(blank=True, null=True)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('packml_state', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('attrs', models.JSONField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='Last time this tag was modified')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this tag was created')),
                ('plc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='industrial_config_manager.plc')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['plc', 'enabled'], name='industrial__plc_id_50c108_idx'), models.Index(fields=['last_modified'], name='industrial__last_mo_c626fa_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='plc',
            index=models.Index(fields=['equipment_id'], name='industrial__equipme_8decd5_idx'),
        ),
        migrations.AddIndex(
            model_name='plc',
            index=models.Index(fields=['driver'], name='industrial__driver__19a243_idx'),
        ),
    ]
