# Generated by Django 5.1.15 on 2026-02-05 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scada_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='area',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='country',
        ),
        migrations.RemoveField(
            model_name='location',
            name='country',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='location',
        ),
        migrations.RemoveField(
            model_name='location',
            name='client',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='manufacturer',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Factory',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Machine',
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
    ]
