# Generated by Django 5.1.15 on 2026-02-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada_manager', '0002_remove_machine_area_remove_manufacturer_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mylayout',
            old_name='button_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='mylayoutstitle',
            old_name='button_name',
            new_name='name',
        ),
    ]
