# Generated by Django 5.1.15 on 2026-02-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada_manager', '0003_rename_button_name_mylayout_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mylayoutstitle',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='mylayoutstitle',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='MyLayOut',
        ),
    ]
