# Generated by Django 5.1.15 on 2026-03-16 11:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada_manager', '0004_alter_mylayoutstitle_options_mylayoutstitle_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('source', models.CharField(choices=[('connection', 'Conexión PLC'), ('local', 'Local')], default='connection', max_length=16)),
                ('equipment', models.CharField(blank=True, default='', max_length=256)),
                ('variable', models.CharField(blank=True, default='', max_length=256)),
                ('datatype', models.CharField(blank=True, choices=[('Float', 'Float'), ('Bool', 'Bool'), ('Int', 'Int'), ('String', 'String'), ('Double', 'Double')], default='Float', max_length=16)),
                ('unit', models.CharField(blank=True, default='', max_length=32)),
                ('address', models.CharField(blank=True, default='', max_length=256)),
                ('node_id', models.CharField(blank=True, default='', max_length=256)),
                ('initial_value', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='scada_manager.mylayoutstitle')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('layout', 'name')},
            },
        ),
    ]
