# Generated by Django 5.1.15 on 2026-01-26 10:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('company', models.CharField(max_length=100, unique=True)),
                ('role', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('client', models.CharField(max_length=100, unique=True)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('date_estimated_start', models.DateField(blank=True, null=True)),
                ('date_estimated_end', models.DateField(blank=True, null=True)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('priority', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('Sin-empezar', 'Sin-empezar'), ('En-proceso', 'En-proceso'), ('Pendiente-revision', 'Pendiente-revision'), ('Validado', 'Validado'), ('Hacer-cambios', 'Hacer-cambios'), ('Finalizado', 'Finalizado')], max_length=50)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('date_estimated_start', models.DateField(blank=True, null=True)),
                ('date_estimated_end', models.DateField(blank=True, null=True)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('priority', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('employees', models.ManyToManyField(to='management.employee')),
                ('fk_project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.project')),
            ],
        ),
    ]
