# Generated by Django 5.1.15 on 2026-03-24 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('site', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('line', models.CharField(blank=True, max_length=100, null=True)),
                ('cell', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'scada_equipment',
                'ordering': ['equipment_id'],
            },
        ),
        migrations.CreateModel(
            name='TagConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('datatype', models.CharField(max_length=50)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='scada_api.equipment')),
            ],
            options={
                'db_table': 'scada_tag_config',
                'ordering': ['equipment', 'variable'],
                'unique_together': {('equipment', 'variable')},
            },
        ),
    ]
