# Generated by Django 5.1.15 on 2026-01-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_manager', '0002_alter_clientmembership_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='scopes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
